Awesome Books (ES6 version)
katarighe/awesome-books-es6 pull request #1
Opened 2023-07-10 16:13 UTC by katarighe

This pull request updates the Awesome Book ES6 project to use the latest version of ES6 features.

In this section, the following activities have been done: 

1. **Cloned** the [old repo](https://github.com/katarighe/awesome-books) to the new one for as `awesome-books-es6.`
2. **Set up** the project using git, linters and other various tools relating to it. 
3. **Updated** the JavaScript syntax to the new ES6 version. 
4. **Added** new features to the project, such as support for classes and modules.
5. **Fixed** any bugs that that were identified in the previous version of the project.
6. **Divided** the index.js file into two different JS files which were created inside the modules. 
7. **Refactored** the functions to arrow (=>) functions on ES6. 
8. **Displayed** the current date below the navigation bar by using the Luxon library.

2023-07-10 19:32 UTC, frempongdev requested changes
# STATUS: CHANGES REQUIRED ♻️ 🚧 

Hi @katarighe   👋🏼 
I'm Frempong.

You've done a great job implementing most of the requirements for this project 🚀, but there are a few changes I recommend be made. You're almost done, keep up the good work! 🤖 🎆 

<img src="https://media.giphy.com/media/yoOotVRp4JMxVTEgDy/giphy.gif"/>

 ## Highlights
✅ Great use of GitHub flow. 💯 
✅ No Linter errors. 🆗  
✅ Your project is documented professionally. 📜 
✅ Great implementation of Modules. ✔️ 


 ## Required Changes ♻️
_Kindly Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-10 19:32 UTC, frempongdev commented on modules/thisbook.js
> +/* eslint-disable */
It is ok to sometimes disable some linters on some lines of code to create an allowance for your application to work. However, it is not a good practice to disable linters for a whole file when you have about 2 or 3 errors to fix. ♻️ 

- [ ] Kndly check and fix the errors being thrown by your linter checker as the main purpose for installing linters is to help your learning and make you are better developer. 👍🏿

2023-07-10 19:32 UTC, frempongdev commented on modules/thisbook.js
> +  }
Good job separating your code into `Modules` as expected in the requirements. 📁 However another requirement of this milestone is to refactor all your JavaScript functions and make them ES6 functions. 

- [ ] Please check and use arrow functions in all the functions as it is the recommended approach for modern development. 🚀

2023-07-10 19:32 UTC, frempongdev commented on modules/thisbook.js
> +  }
- [ ] Kindly check and fix the function to add books as it is not working as expected. 👍🏿 

### Please check application behavior below ⬇️ 
![cannot add book](https://github.com/katarighe/awesome-books-es6/assets/117144028/56bdbc37-2240-49ac-ad4b-af889d960369)

2023-07-10 19:32 UTC, frempongdev commented on index.html
> +    </header>
Great implementation of dynamic display of elements, including the add book page. 🔥 However there seem to be a bug that comes along with the implementation. 

- [ ] Kindly make sure that the `Add Book` navigation link in your `Navbar` does not also disappear when you are hiding the book form. 

### Please check below ⬇️ 
![missing add book](https://github.com/katarighe/awesome-books-es6/assets/117144028/5353ccbd-dddb-4e81-8ccf-0b99e6e039fd)

2023-07-10 19:32 UTC, frempongdev commented on index.html
> +    </footer>
You have done a good job using a footer in this milestone. The footer however does not seem to stay as the foot of the screen. 😢 

- [ ] Kindly consider using `CSS position properties` like `fixed` or absolute to keep it at the bottom of the screen. ⬇️ 

![image](https://github.com/katarighe/awesome-books-es6/assets/117144028/b163b447-741f-4812-971d-602bbecd2981)

2023-07-11 10:56 UTC, mckent05 approved these changes
Hi @katarighe, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions
- Please note that to make your repo more professional, it is advised that your branch name should be descriptive, it could describe a feature or action you are working on. In this case, for example: `refactor_using_es6`. Please note this 👍 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-11 10:59 UTC, merged